# auto tag patch releases on pull-request merge
# status of unit tests does not matter
# 

name: autotag

on:
  # tmp
  push:
  # https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request
  pull_request:
    types: [closed]
    branches:
      # TODO: should be #*.*# type of match - if not possible then check in first step else `exit 1`
      - main

jobs:
  myaction:
    name: 'My action'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Check if is pull-request merge event
        run: |
          if [ "${{ github.event.action }}" != "Closed" ] || [ "${{ github.event.pull_request.merged }}" != "true" ]; then
            echo "Not a pull-request merge event, existing"
            exit 1
          fi

      # Use `fetch-depth: 0` so that `git tag` works as expected
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: yaml

      - name: Get current patch number
        run: |
          # Auto tag a new patch release
          # TODO: Am running on main branch, normally would have a `1.0` like branch so would need to detect that via github.ref .replace '^refs/heads/' ''
          MINOR_BRANCH=1.0
          
          # show json associated with the event, can be parsed with jq()
          # cat $GITHUB_EVENT_PATH
                    
          # Echo the current patch verison
          /usr/bin/git tag >> tags.txt
          cat << EOF > run.php
          <?php
          \$arr = [];
          foreach (explode("\n", file_get_contents('tags.txt')) as \$tag) {
            if (!preg_match('#^([0-9]+)\.([0-9]+)\.([0-9]+)\$#', \$tag, \$m)) continue;
            list(\$z, \$a, \$b, \$c) = \$m;
            if ("\$a.\$b" != '$MINOR_BRANCH') continue;
            \$arr[] = (int) "\$c";
          }
          if (count(\$arr) == 0) exit(0);
          sort(\$arr);
          echo \$arr[count(\$arr) - 1];
          EOF
          CURR_PATCH_N=$(php run.php)
          if [ "$CURR_PATCH_N" == "" ]; then echo "No existing semver tag found for minor branch $MINOR_BRANCH, exiting" && exit 0; fi
          NEXT_PATCH_N=$((CURR_PATCH_N+1))
          CHANGELOG=$(git log --oneline --pretty=format:"* %s (%an) - %h" --no-merges $MINOR_BRANCH.$CURR_PATCH_N...main)

      - name: Bump version and push tag
        uses: laputansoft/github-tag-action@v4.6
        with:
          github_token: ${{ env.github-token }}
          tag: ${{ steps.package-version.outputs.version }}
          
                    
          
          
