# auto tag patch releases on pull-request merge
# status of unit tests does not matter
# 

name: autotag

on:
  # tmp
  push:
  # https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  myaction:
    name: 'My action'
    runs-on: ubuntu-latest
    steps:

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: yaml

      - name: My step
        # if: github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          # Auto tag a new patch release
          # Am running on main branch, normally would have a `1.0` like branch so would need to detect that via github.ref .replace '^refs/heads/' ''
          
          # show json associated with the event, can be parsed with jq()
          # cat $GITHUB_EVENT_PATH
          
          wget -O tags.json https://api.github.com/repos/${{ github.repository }}/tags
          cat << EOF > run.php
          <?php
          \$j = json_decode(file_get_contents('tags.json'));
          print_r(\$j);
          EOF
          php run.php
          
          # Get latest patch tag
          
          # Increment it
          
          
          
