# https://docs.github.com/en/actions
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

# https://github.com/silverstripe/silverstripe-travis-shared/blob/master/config/base.yml

name: tests

on:
  push:
  pull_request:
  # every day at midnight:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: SS_mysite
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      # fail-fast: true
      matrix:
        include:
          - php: '7.4'

    # name: PHP ${{ matrix.php }} - ${{ matrix.stability }}
    name: PHP ${{ matrix.php }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          # dev is used to install phpize which is used by pecl
          # cli, dev
          extensions: curl, dom, gd, intl, json, ldap, mbstring, mysql, tidy, xdebug, zip
          tools: composer:v2
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          php-version: ${{ matrix.php }}

      # this should only be done for behat
      - name: Install and start Apache
        run: |
          # sudo apt update
          # sudo apt install -y apache2 # already the latest
          #pwd
          #ls
          #ls /var/www/html
          php .github/things/apache2.php
          #cat 000-default.conf
          sudo cp 000-default.conf /etc/apache2/sites-enabled/000-default.conf
          #cat /etc/apache2/sites-enabled/000-default.conf
          # sudo adduser $(whoami) www-data
          # sudo adduser $(whoami) root
          # sudo adduser root www-data
          # sudo chown -R www-data:www-data /etc/apache2/sites-available/
          # sudo chmod -R 777 /etc/apache2/sites-available/
          # sudo chown -R www-data:www-data $(pwd)
          # sudo chmod -R 777 $(pwd)
          # ls -al
          # cp .github/things/docker_apache_default /etc/apache2/sites-enabled/000-default.conf
          sudo systemctl restart apache2
          curl -I 127.0.0.1

      # COMPORER_ROOT_VERSION - need to get access to the current branch in github actions
      #  - if [[ "$TRAVIS_BRANCH" =~ ^[1-9]$ ]] || [[ "$TRAVIS_BRANCH" =~ ^[1-9]\.[0-9]+$ ]]; then export COMPOSER_ROOT_VERSION="${TRAVIS_BRANCH}.x-dev"; elif [[ "$TRAVIS_BRANCH" =~ ^[1-9]\.[0-9]+\.[0-9]+ ]]; then export COMPOSER_ROOT_VERSION="${TRAVIS_BRANCH}"; else export COMPOSER_ROOT_VERSION="dev-${TRAVIS_BRANCH}"; fi
      # - echo "$COMPOSER_ROOT_VERSION"

      - name: Composer
        run: |
          composer require silverstripe/installer:^4 --no-update --prefer-dist
          composer require silverstripe/recipe-testing:^1 --no-update --prefer-dist
          composer update --prefer-dist --no-interaction --no-progress
          mkdir artifacts
          cp composer.json artifacts
          cp composer.lock artifacts

      - name: Set permissions
        run: |
          ls -al
          echo $(whoami)
          sudo adduser $(whoami) www-data
          #sudo adduser $(whoami) root
          #sudo adduser root www-data
          sudo chown -R www-data:www-data /etc/apache2/sites-available/
          sudo chown -R www-data:www-data $(pwd)
          ls -al

      - name: Create .env
        run: |
          touch .env
          echo 'SS_DATABASE_CLASS=MySQLDatabase' >> .env
          echo 'SS_DATABASE_SERVER=127.0.0.1' >> .env
          echo 'SS_DATABASE_PORT=3306' >> .env
          echo 'SS_DATABASE_USERNAME=root' >> .env
          echo 'SS_DATABASE_PASSWORD=root' >> .env
          echo 'SS_DATABASE_NAME=SS_mysite' >> .env
          echo 'SS_ENVIRONMENT_TYPE=dev' >> .env
          echo 'SS_BASE_URL=http://localhost' >> .env

      - name: Run dev/build flush=1
        run: |
          vendor/bin/sake dev/build flush=1

      - name: Run phpunit
        run: |
          vendor/bin/phpunit --verbose

      - name: Make new behat.yml
        run: |
          php .github/things/behat.php
          cp behat.yml artifacts
          
      - name: Test webserver
        run: |
          curl http://localhost
      # - name: Start chromedriver
      #   run: |
      #     #which google-chrome
      #     #google-chrome --version
      #     #which chromedriver
      #     #chromedriver -v
      #     # --log-level=INFO
      #     nohup sh -c "chromedriver --allowed-ips='' --port=9515 --log-path=artifacts/chromedriver.log --verbose" > /dev/null 2>&1 &

      - name: Run behat
        run: |
          nohup sh -c "chromedriver --allowed-ips='' --port=9515 --log-path=artifacts/chromedriver.log --verbose" > /dev/null 2>&1 &
          vendor/bin/behat octopus

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: artifacts
          path: artifacts
