# https://docs.github.com/en/actions
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

# https://github.com/silverstripe/silverstripe-travis-shared/blob/master/config/base.yml

name: tests

on:
  push:
  pull_request:
  # every day at midnight:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: SS_mysite
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      # fail-fast: true
      matrix:
        include:
          - php: '7.4'

    # name: PHP ${{ matrix.php }} - ${{ matrix.stability }}
    name: PHP ${{ matrix.php }}

    steps:
      # disabling this because ran into dependency issues trying to install libapache2-mod-php
      # Should conditionally use this for non-behat jobs
      # - name: Setup PHP
      #   uses: shivammathur/setup-php@v2
      #   with:
      #     php-version: ${{ matrix.php }}
      #     extensions: curl, dom, gd, intl, json, ldap, mbstring, mysql, tidy, xdebug, zip
      #     tools: composer:v2
      #     coverage: none

      - name: Checkout code
        uses: actions/checkout@v2
        # with:
        #   php-version: ${{ matrix.php }}

      # This is kind of slow at around 44 seconds, it's only because I was having
      # issues with libapache2-mod-php which is needed for behat
      # Ideally would use shivammathur/setup-php@v2 instead which is far faster
      # could possibly just use this installation method conditional on it being a behat job
      - name: Install PHP
        run: |
          # Make all php versions other than the current main version available
          sudo apt update && sudo sudo apt install -y software-properties-common
          sudo add-apt-repository -y ppa:ondrej/php
          sudo add-apt-repository -y ppa:ondrej/apache2
          sudo apt update
          sudo apt install libapache2-mod-php${{ matrix.php }} php${{ matrix.php }} php${{ matrix.php }}-cli php${{ matrix.php }}-curl  php${{ matrix.php }}-dom php${{ matrix.php }}-gd php${{ matrix.php }}-intl php${{ matrix.php }}-json php${{ matrix.php }}-ldap php${{ matrix.php }}-mbstring php${{ matrix.php }}-mysql php${{ matrix.php }}-tidy php${{ matrix.php }}-xdebug php${{ matrix.php }}-zip
          # This this verison of PHP instead of the default ubuntu php8.0 install
          sudo rm /etc/alternatives/php
          sudo ln -s /usr/bin/php${{ matrix.php }} /etc/alternatives/php
          # Test
          php -v

      # This only needs to be done if not using shivammathur/setup-php@v2
      - name: Install composer
        run: |
          php -r "copy('https://composer.github.io/installer.sig', 'installer.sig');"
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php -r "if (hash_file('sha384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          if [ -f composer-setup.php ]; then php composer-setup.php && rm composer-setup.php; fi
          rm installer.sig
          sudo mv composer.phar /usr/local/bin/composer

      # COMPORER_ROOT_VERSION - need to get access to the current branch in github actions
      #  - if [[ "$TRAVIS_BRANCH" =~ ^[1-9]$ ]] || [[ "$TRAVIS_BRANCH" =~ ^[1-9]\.[0-9]+$ ]]; then export COMPOSER_ROOT_VERSION="${TRAVIS_BRANCH}.x-dev"; elif [[ "$TRAVIS_BRANCH" =~ ^[1-9]\.[0-9]+\.[0-9]+ ]]; then export COMPOSER_ROOT_VERSION="${TRAVIS_BRANCH}"; else export COMPOSER_ROOT_VERSION="dev-${TRAVIS_BRANCH}"; fi
      # - echo "$COMPOSER_ROOT_VERSION"

      - name: Composer
        run: |
          composer require silverstripe/installer:^4 --no-update --prefer-dist
          composer require silverstripe/recipe-testing:^1 --no-update --prefer-dist
          composer update --prefer-dist --no-interaction --no-progress
          mkdir artifacts
          cp composer.json artifacts
          cp composer.lock artifacts

      - name: Create .env
        run: |
          touch .env
          echo 'SS_DATABASE_CLASS=MySQLDatabase' >> .env
          echo 'SS_DATABASE_SERVER=127.0.0.1' >> .env
          echo 'SS_DATABASE_PORT=3306' >> .env
          echo 'SS_DATABASE_USERNAME=root' >> .env
          echo 'SS_DATABASE_PASSWORD=root' >> .env
          echo 'SS_DATABASE_NAME=SS_mysite' >> .env
          echo 'SS_ENVIRONMENT_TYPE=dev' >> .env
          # http://localhost should be correct. 
          # - http://localhost:8080 fails in behat with - net::ERR_CONNECTION_REFUSED
          # - http://127.0.0.1 fails in behat with - Failed to connect to 127.0.0.1 port 9515: Connection refused (Behat\Mink\Exception\DriverException)
          # - http://0.0.0.0 works the same as http://localhost
          echo 'SS_BASE_URL=http://localhost' >> .env
          #echo 'SS_BASE_URL=http://0.0.0.0' >> .env

      - name: dev/build flush=1
        run: |
          vendor/bin/sake dev/build flush=1

      - name: phpunit
        run: |
          vendor/bin/phpunit --verbose

      # this should only be done for behat
      - name: Configure apache
        run: |
          # apache2 is installed and running by default in ubuntu
          # Update dir.conf to use index.php as the primary index doc
          sudo cp .github/things/dir.conf /etc/apache2/mods-enabled/dir.conf
          # This script will create a 000-default.conf file with the pwd as the DocumentRoot
          php .github/things/apache2.php
          sudo cp 000-default.conf /etc/apache2/sites-enabled/000-default.conf
          sudo a2enmod rewrite
          sudo systemctl restart apache2

          # Try doing bizarre stuff
          touch hosts
          echo '0.0.0.0 localhost' >> hosts
          sudo cp hosts /etc/hosts

          # Permissions
          sudo chown -R www-data:www-data .
          # chmod - a bit brute force, still need to allow the default runner:docker user to be
          # able to create files such as artifacts
          # Was having issues adding the current 'runner' user to the www-data group - possibly need to log out
          # and log back in again for it to take effect, which isn't possible in this context
          sudo chmod -R 0777 .

          # Test that webserver is working
          curl http://localhost

      - name: curl /
        run: |
          curl http://localhost/

      - name: curl /about-us
        run: |
          curl http://localhost/about-us

      - name: curl /admin
        run: |
          # -L means follow redirects
          curl -L http://localhost/admin

      - name: behat
        run: |
          # This script will update behat.yml to work with headless chrome
          php .github/things/behat.php
          cp behat.yml artifacts
          nohup sh -c "chromedriver --allowed-ips='' --port=9515 --log-path=artifacts/chromedriver.log --log-level=INFO" > /dev/null 2>&1 &
          vendor/bin/behat octopus

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: artifacts
          path: artifacts
