# https://docs.github.com/en/actions
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

# https://github.com/silverstripe/silverstripe-travis-shared/blob/master/config/base.yml

name: tests

on:
  push:
  pull_request:
  # every day at midnight:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: SS_mysite
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      # fail-fast: true
      matrix:
        include:
          - php: '7.4'

    # name: PHP ${{ matrix.php }} - ${{ matrix.stability }}
    name: PHP ${{ matrix.php }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          # dev is used to install phpize which is used by pecl
          # cli, dev
          extensions: curl, dom, gd, intl, json, ldap, mbstring, mysql, tidy, xdebug, zip
          tools: composer:v2
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          php-version: ${{ matrix.php }}

      # COMPORER_ROOT_VERSION - need to get access to the current branch in github actions
      #  - if [[ "$TRAVIS_BRANCH" =~ ^[1-9]$ ]] || [[ "$TRAVIS_BRANCH" =~ ^[1-9]\.[0-9]+$ ]]; then export COMPOSER_ROOT_VERSION="${TRAVIS_BRANCH}.x-dev"; elif [[ "$TRAVIS_BRANCH" =~ ^[1-9]\.[0-9]+\.[0-9]+ ]]; then export COMPOSER_ROOT_VERSION="${TRAVIS_BRANCH}"; else export COMPOSER_ROOT_VERSION="dev-${TRAVIS_BRANCH}"; fi
      # - echo "$COMPOSER_ROOT_VERSION"

      - name: Composer
        run: |
          composer require silverstripe/installer:^4 --no-update --prefer-dist
          composer require silverstripe/recipe-testing:^1 --no-update --prefer-dist
          composer update --prefer-dist --no-interaction --no-progress
          mkdir artifacts
          cp composer.json artifacts
          cp composer.lock artifacts

      - name: Create .env
        run: |
          touch .env
          echo 'SS_DATABASE_CLASS=MySQLDatabase' >> .env
          echo 'SS_DATABASE_SERVER=127.0.0.1' >> .env
          echo 'SS_DATABASE_PORT=3306' >> .env
          echo 'SS_DATABASE_USERNAME=root' >> .env
          echo 'SS_DATABASE_PASSWORD=root' >> .env
          echo 'SS_DATABASE_NAME=SS_mysite' >> .env
          echo 'SS_ENVIRONMENT_TYPE=dev' >> .env
          echo 'SS_BASE_URL=http://localhost' >> .env

      - name: Run dev/build flush=1
        run: |
          vendor/bin/sake dev/build flush=1

      - name: Run phpunit
        run: |
          vendor/bin/phpunit --verbose

      # this should only be done for behat
      - name: Configure apache
        run: |
          # apache2 is installed and running by default in ubuntu
          sudo apt install libapache2-mod-php${{ matrix.php }}
          sudo echo > 'DirectoryIndex index.php index.html index.htm' > /etc/apache2/mods-enabled/dir.conf
          # This script will create a 000-default.conf file with the pwd as the DocumentRoot
          php .github/things/apache2.php
          sudo cp 000-default.conf /etc/apache2/sites-enabled/000-default.conf
          # Files in the pwd with have the user:group runner:docker, so add www-data to the docker group
          sudo adduser www-data docker
          sudo systemctl restart apache2
          # Test that webserver is working
          curl http://localhost

      - name: Run behat
        run: |
          # This script will update behat.yml to work with headless chrome
          php .github/things/behat.php
          cp behat.yml artifacts
          nohup sh -c "chromedriver --allowed-ips='' --port=9515 --log-path=artifacts/chromedriver.log --verbose" > /dev/null 2>&1 &
          vendor/bin/behat octopus

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: artifacts
          path: artifacts
