# https://docs.github.com/en/actions
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

# https://github.com/silverstripe/silverstripe-travis-shared/blob/master/config/base.yml

name: tests

on:
  push:
  pull_request:
  # every day at midnight:
  schedule:
    - cron: '0 0 * * *'

jobs:
  linux_tests:
    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: SS_mysite
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: true
      matrix:
        include:
          - php: '7.4'

    # name: PHP ${{ matrix.php }} - ${{ matrix.stability }}
    name: PHP ${{ matrix.php }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          # dev is used to install phpize which is used by pecl
          # cli, dev
          extensions: curl, dom, gd, intl, json, ldap, mbstring, mysql, tidy, xdebug, zip
          tools: composer:v2
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Require silverstripe/installer
        run: composer require silverstripe/installer:^4  --no-update --prefer-dist

      - name: Composer dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: dev/build
        run: vendor/bin/sake dev/build flush=1

      - name: Execute tests
        run: vendor/bin/phpunit --verbose
        env:
          SS_DATABASE_CLASS: MySQLDatabase
          SS_DATABASE_SERVER: 127.0.0.1
          SS_DATABASE_PORT: 3306
          SS_DATABASE_USERNAME: root
          SS_DATABASE_PASSWORD: root
          SS_DATABASE_NAME: SS_mysite
          SS_ENVIRONMENT_TYPE: dev
          SS_BASE_URL: http://localhost:8080/
          # DISPLAY: ":99"
          # XVFBARGS ":99 -ac -screen 0 1024x768x16"

      # - name: Store artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: logs
      #     ...
