# Because we're checking out admin 1 only, we must only run this script on next-minor branches

name: JS upgrade (next-minor branch only)

on:
  # TODO: cron, not push
  push:

jobs:
  mainjob:
    name: 'Main job'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=version::$(cat .nvmrc)
        id: read-nvm

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.read-nvm.outputs.version }}

      - name: Install yarn
        run: npm install --global yarn

      - name: Install admin JS
        if: github.event.repository.name != 'admin'
        run: |
          DIR=$(pwd)
          cd ..
          git clone https://github.com/silverstripe/silverstripe-admin.git
          mv silverstripe-admin admin
          cd admin
          git checkout 1
          yarn install
          cd $DIR

      - name: Update yarn.lock
        run: |
          # Run yarn upgrade and build js

          # update yarn.lock
          yarn upgrade

      - name: Build JS
        run: |
          yarn build
          git status
