name: JS upgrade

on:
  # TODO: cron, not push
  push:

jobs:
  mainjob:
    name: 'Main job'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=version::$(cat .nvmrc)
        id: read-nvm

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.read-nvm.outputs.version }}

      - name: Install yarn
        run: npm install --global yarn

      - name: Checkout admin
        # if ! admin
        run: |
          cd ..
          # TODO: determine correct version with github.ref
          git clone https://github.com/silverstripe/silverstripe-admin.git
          yarn install

      # - name: Upgrade JS
      #   run: |
      #     # Run yarn upgrade and build js

      #     # update yarn.lock
      #     yarn upgrade

      - name: Build JS
        run: |
          yarn build
          git status
