name: JS upgrade

on:
  # TODO: cron, not push
  push:

jobs:
  mainjob:
    name: 'Main job'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup npm via .nvmrc
        uses: dcodeIO/setup-node-nvm@master

      - name: Install yarn
        run: |
          npm install --global yarn

      - name: Upgrade JS
        run: |
          # Run yarn upgarde and build js

          yarn upgrade

          git diff

